name: Maven Build

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn --batch-mode clean verify

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-jar
          path: /server/plugins/*.jar
